version: '3.9'
services:
  web:
    depends_on:
      - redis
    image: devops_test:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     REDIS_ADDR: redis:6379
    restart: on-failure
    ports:
      - "8080:8080"
  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
