---
apiVersion: v1
kind: Service
metadata:
  name: devops-test-app-service
  labels:
    app: devops-test
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: devops-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-test
  template:
    metadata:
      labels:
        app: devops-test
    spec:
      containers:
        - name: app
          image: sdoninja/devops_test:1.0
          env:
            - name: REDIS_ADDR
              value: "devops-test-redis-service:6379"
          ports:
            - name: http-8080
              containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: devops-test-redis-expose-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 9121
      targetPort: 9121
  type: ClusterIP
